Repository pulse-browser/browser, pull requests merged in 2022-11, with the labels that each got.

#135 Upgrade Firefox to 106.0.5
  gluon.json
  src/browser/app/profile/firefox-js.patch
  src/browser/components/BrowserGlue-jsm.patch
  src/browser/components/moz-build.patch
  src/browser/components/welcome/welcome.js
Labels: upgrade

#147 Allow for signed and unsigned uBlock origin releases + update uBlock
  .vscode/settings.json
  gluon.json
Labels: bug, dependencies

#155 Update Firefox to 107.0 & uBlock to 1.45.2
  .github/PULL_REQUEST_TEMPLATE/ff_update.md
  gluon.json
  package.json
  src/browser/app/profile/firefox-js.patch
  src/browser/base/content/browser-menubar-inc.patch
  src/browser/base/content/browser-sidebar-js.patch
  src/browser/themes/BuiltInThemeConfig-sys-mjs.patch
  src/browser/themes/ThemeVariableMap-jsm.patch
  src/browser/themes/ThemeVariableMap-sys-mjs.patch
  src/browser/themes/pulse/content/downloads.css
  src/browser/themes/pulse/jar.inc.mn
  src/browser/themes/pulse/sidebar_tabs.css
  src/browser/themes/shared/browser-shared-css.patch
  src/browser/themes/shared/downloads/allDownloadsView-inc-css.patch
  src/browser/themes/shared/jar-inc-mn.patch
  src/toolkit/modules/LightweightThemeConsumer-jsm.patch
  src/toolkit/modules/LightweightThemeConsumer-sys-mjs.patch
  src/toolkit/modules/moz-build.patch
Labels: dependencies
