Repository pulse-browser/browser, pull requests merged in 2022-01, with the labels that each got.

#5 🌐 Add i10n for welcome page
  src/browser/components/welcome/jar.mn
  src/browser/components/welcome/welcome.html
  src/browser/locales/en-US/browser/welcome.ftl
Labels: Refinement, i10n

#18 :lipstick: UI polish for the welcome page
  CHANGELOG.md
  src/browser/components/welcome/welcome.js
Labels: Refinement, Design

#27 📝 README
  README.md
Labels: documentation

#31 ⬆️ Update newtab page
  melon.json
Labels: enhancement, Refinement
